# Generated by Django 5.0.2 on 2024-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_producto_alter_task_datecompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('ventas_realizadas', models.IntegerField()),
                ('cliente_importante', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tabla_productos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
