# Generated by Django 5.0.2 on 2024-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=50, verbose_name='Equipo')),
                ('linea', models.CharField(max_length=50, verbose_name='Linea')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tecnico', models.CharField(max_length=50, verbose_name='Técnico')),
                ('numero_empleado', models.CharField(max_length=50, verbose_name='Número de Empleado')),
            ],
        ),
    ]
