# Generated by Django 5.0.2 on 2024-05-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='equipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='linea',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='numero_empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico',
            field=models.CharField(max_length=50),
        ),
    ]
