# Generated by Django 5.0.2 on 2024-05-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_sala_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
