# Generated by Django 5.0.2 on 2024-05-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_linea_piloto'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.humanos')),
            ],
        ),
    ]
